### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by yzc111** [jiho283/FactKG#1]
Hello, when can you publish the baseline?

**Comment by jiho283** [comment]
Sorry for the late sharing. We will be able to share it in two weeks.

**Comment by yzc111** [comment]
thank you for your reply

**Comment by yzc111** [comment]
Hello，when you publish the baseline with evidence?

**Comment by jiho283** [comment]
I'm so sorry for the delay. I will upload the code next week after fixing some errors.

**Comment by jiho283** [comment]
I updated the baseline!

**Comment by yzc111** [comment]
thank you !
