### ISSUE TITLE
evidence from dbpedia

### ISSUE THREAD

**Issue by yzc111** [jiho283/FactKG#2]
an subject "Prasanna_Acharya" in the evidence, the triple is "Prasanna_Acharya,  spouse, Prafulla_Chandra_Ghadei" but, if we use dbpedia to extract the object,  dbpedia['Prasanna_Acharya']['spouse'] can't find the objcet "Prafulla_Chandra_Ghadei", it is different from the evidence. why?

**Comment by jiho283** [comment]
The statement you mentioned is a false claim, so the corresponding triple does not exist in dbpedia. For each claim, if it's a true claim, the triples that support that claim exist in dbpedia. However, for a false claim, the corresponding triples do not exist in dbpedia. Therefore, we have structured the evidence not in the form of a [h, r, t] triple but in the form of relations connected to each entity.

**Comment by yzc111** [comment]
thank you for your response

**Comment by yzc111** [comment]
sorry, these is a example in train dataset, the lable is true, but can not get the object from dbpedia, according the evidence:
<{'Frank_McPhee_(American_football)': [['team']], 'Chicago_Cardinals_(NFL,_1920–1959)': [['~team']]}>

**Comment by jiho283** [comment]
Thank you for your interest in FactKG. 
 The claim you mentioned is "I wish that Frank McPhee (American football) plays for the Chicago Cardinals (NFL, 1920–1959)," whereas the original sentence is "Frank McPhee (American football) plays for the Chicago Cardinals (NFL, 1920–1959)." The corresponding triple ['Frank_McPhee_(American_football)', 'team', 'Chicago_Cardinals_(NFL,_1920–1959)'] does not exist in dbpedia. 
 However, this claim includes "I wish that", indicating a presupposition. This is evident when we say "I wish that <<statement A>>" in situations where <<statement A>> is false. Thus, when <<statement A>> is false, "I wish that <<statement A>>" becomes true. Therefore, even if there is no corresponding triple for <<statement A>>, there can still be a true claim. Please refer to the paper for more details.

**Comment by yzc111** [comment]
I understand it, thanks

**Comment by yzc111** [comment]
{"New Zealand's Ardmore Airport's 3rd runway is made of poaceae.": [["Ardmore_Airport_(New_Zealand)", "r3Surface", "Poaceae"], ["Poaceae", "order", "Commelinids"]]}
