### ISSUE TITLE
Using the latest version of DBPedia

### ISSUE THREAD

**Issue by gangiswag** [jiho283/FactKG#3]
Is there a way to run the system with the latest version of DBPedia? i.e. use the most recent knowledge graph at inference

**Comment by jiho283** [comment]
First of all, thank you for your interest in our dataset. To perform inference on the latest DBpedia, you need to download the latest version of DBpedia from https://www.dbpedia.org/resources/ and process the KG in dictionary form. Unfortunately, our FactKG does not provide the setting yet.

**Comment by gangiswag** [comment]
Thanks for the answer @jiho283 
Would your system work out of the box if I replaced the underlying KG with the most recent version of DBPedia?

 I was concerned of unseen relations popping up when using latest DBPedia for inference, since model was trained on DBPedia 2015

**Comment by gangiswag** [comment]
@jiho283 : Also I was curious on how easy/hard it is to adapt the system to work on the latest version of Wikidata.

The downstream fact verification system can be potentially replaced with an instruction-tuned LLM, but for the subgraph retrieval system, do you have any thoughts on how the current system can be extended to Wikidata?

**Comment by jiho283** [comment]
1. The model trained on our train data, such as the GEAR baseline we implemented, has been limitedly used for about 500 relations that we use. Therefore, if you use the latest DBpedia, it may not apply when a relation is not in these 500 relations. The method I recommend is to use an LLM to give a few-shot of examples existing in the train data and to infer on the latest data, then I believe it could be adapted for use. In fact, in the study called KG-GPT (https://github.com/jiho283/KG-GPT), I obtained decent performance using a few examples on this dataset.

2. As mentioned above, if you want to expand to Wikidata and conduct experiments, you could also utilize an LLM for subgraph retrieval. It may be difficult to set up a test set based on Wikidata (e.g., preprocessing), but if you leverage the generalization ability of the LLM, it should be sufficiently adaptable.
