### ISSUE TITLE
The label of the example in readme

### ISSUE THREAD

**Issue by ShuzhouYuan** [jiho283/FactKG#4]
Hello,
in the example of the data, I don't really understand why the label of the following claim is False. It seems all the evidence support the claim.
```
{
 'Adam McQuaid weighed 94.8024 kilograms and is from Pleasant Springs, Wisconsin.': 
   {
   'Label': [False],
    'Entity_set': ['Adam_McQuaid', '"94802.4"', 'Pleasant_Springs,_Wisconsin'],
    'Evidence': {'Adam_McQuaid': [['weight'], ['placeOfBirth']],
     '"94802.4"': [['~weight']],
     'Pleasant_Springs,_Wisconsin': [['~placeOfBirth']]},
    'types': ['coll:model', 'num2', 'substitution', 'multi claim']
    }
}
```

**Comment by jiho283** [comment]
Thank you for your interest in our research.

It is possible to misunderstand if one only looks at the evidence. The evidence graph in question is simply a graph that corresponds one-to-one with the content of the claim, and the triples may not actually exist in the KG. For example, the triple [Adam_McQuaid, placeOfBirth, Pleasant_Springs,_Wisconsin] in the evidence graph of this example does not exist in the actual KG.
